FROM golang:1.22-alpine AS builder
WORKDIR /usr/src/app
RUN go mod init hello
COPY hello.go .
RUN go mod download && go mod verify
RUN go build -v -o /usr/local/bin/app ./...
#CMD ["app"]

FROM scratch
COPY --from=builder /usr/local/bin/app /usr/local/bin/app
CMD ["/usr/local/bin/app"]
